version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - '/path/to/your/local/mariadb_data:/bitnami/mariadb'
  application:
    image: 'bitnami/drupal:latest'
    ports:
      - '10080:80'
      - '10443:443'
    volumes:
      - '/path/to/your/local/drupal_data:/bitnami/drupal'
      - '/path/to/your/local/apache_data:/bitnami/apache'
    depends_on:
      - mariadb
