version: '3'
services:
  redis:
    restart: always
    image: sameersbn/redis:latest
    volumes:
        - /srv/docker/gitlab/redis:/var/lib/redis

  # postgresql:
  #   restart: always
  #   image: sameersbn/postgresql:9.6-2
  #   volumes:
  #   - /srv/docker/gitlab/postgresql:/var/lib/postgresql:Z
  #   environment:
  #   - DB_USER=gitlab
  #   - DB_PASS=password
  #   - DB_NAME=gitlabhq_production
  #   - DB_EXTENSION=pg_trgm

  mysql:
    restart: always
    image: sameersbn/mysql:latest
    volumes:
        - /srv/docker/gitlab/mysql:/var/lib/mysql
    environment:
        - DB_NAME=gitlabhq_production
        - DB_USER=gitlab
        - DB_PASS=password

  gitlab:
    restart: always
    image: sameersbn/gitlab:9.1.2
    ports:
        - "10080:80"
        - "10022:22"
    volumes:
        - /srv/docker/gitlab/gitlab:/home/git/data
    links:
        - redis:redis
        - mysql:mysql
    environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379

        - DB_ADAPTER=mysql2
        - DB_HOST=mysql
        - DB_PORT=3306
        - DB_NAME=gitlabhq_production
        - DB_USER=gitlab
        - DB_PASS=password

        - TZ=Asia/Beijing
        - GITLAB_TIMEZONE=Beijing

        - GITLAB_HOST=localhost
        - GITLAB_PORT=10080
        - GITLAB_SSH_PORT=10022
        - GITLAB_RELATIVE_URL_ROOT=
        - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string
        - GITLAB_SECRETS_SECRET_KEY_BASE=long-and-random-alphanumeric-string
        - GITLAB_SECRETS_OTP_KEY_BASE=long-and-random-alphanumeric-string
